baseurl = "https://test.plevy.fr/"
languageCode = "en"
title = "plevy.fr"
theme = "plevy"

[Params]
    favicon = "icon.png"

DefaultContentLanguage = "en"
copyright = "plevy.fr"

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = true

[privacy.instagram]
disable = true

[privacy.twitter]
disable = true

[privacy.vimeo]
disable = true

[privacy.youtube]
disable = true

[languages.en]
languageName = "EN"
languageCode = "en"
weight = 1

[[languages.en.menu.main]]
identifier = "cv"
name = "resume"
title = "resume"
url = "/cv"
weight = 1

[[languages.en.menu.main]]
identifier = "publications"
name = "publications"
title = "publications"
url = "/publications"
weight = 2

[[languages.en.menu.main]]
identifier = "contact"
name = "contact"
title = "contact"
url = "/contact"
weight = 3

[languages.fr]
languageName = "FR"
languageCode = "fr"
weight = 2

[[languages.fr.menu.main]]
identifier = "cv"
name = "curriculum vitae"
title = "curriculum vitae"
url = "/cv"
weight = 1

[[languages.fr.menu.main]]
identifier = "publications"
name = "publications"
title = "publications"
url = "/publications"
weight = 2

[[languages.fr.menu.main]]
identifier = "contact"
name = "contact"
title = "contact"
url = "/contact"
weight = 3
